### ISSUE TITLE
Publishing Tasks Checklist

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-mongodb-intro#68]
Publishing Tasks
- [x] Update the release date
- [x] Make sure that CONTRIBUTING.md and License files exist
- [x] Rename `dev` to `prod` branch
- [x] Create `staging` branch from `prod` branch
- [x] Rename the guide repo
   - guide-mongodb-intro
- [x] Check that tags and categories are updated
  - https://github.com/OpenLiberty/guides-common
- [x] Refresh the staging site (either the following) and verify 
- [x] If staging site has no problem, request to refresh openliberty.io site
- [x] For `prod` branch, add a tag by creating a new release for this repo with name "1st-release"
